class Article < ActiveRecord::Base
  # extends ...................................................................
  extend FriendlyId

  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :category_id, :title, :content

  # relationships .............................................................
  belongs_to :category

  # validations ...............................................................
  validates :title, :presence => { :message => "请填写标题"}
  validates :content, :presence => { :message => "请填写内容"}

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_list :scope => :category
  friendly_id :name_pinyin, use: :slugged
  
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
  def name_pinyin
    Pinyin.t(title)
  end
end
