class Article < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :category_id, :title, :content

  # relationships .............................................................
  belongs_to :category

  # validations ...............................................................
  validates :category_id, :presence => { :message => "请选择类别"}
  validates :title, :presence => { :message => "请填写标题"}
  validates :content, :presence => { :message => "请填写内容"}

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_list :scope => :category
  
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
