class Category < ActiveRecord::Base
  # extends ...................................................................
  extend FriendlyId
  
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name

  # relationships .............................................................
  has_many :articles, :order => "position"

  # validations ...............................................................
  validates :name, :uniqueness => true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  has_ancestry
  friendly_id :name_pinyin, use: :slugged

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
  def name_pinyin
    Pinyin.t(name)
  end
end
